name: birthdayreminder
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  objectbox: ^4.0.2
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  objectbox_generator: any

flutter:

  uses-material-design: true
